package es.unizar.webeng.hello;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
/*
 * Class that represents the data stored.
 * Uses the <code>@Entity</code> to indicate that it'll function as an JPA entity.
 * We can see this as what would've been the table Text in a relational database.
 */
@Entity
public class Text {
    /*
     * Annotation <code> @Id </code> is used to notify JPA the Text's id.
     * Also <code> @GeneratedValue </code> declaes that such id will be autogenerated.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String msg;

    protected Text() {}

    public Text(String someText) {
        this.msg = someText;
    }

    public String getMsg() {
        return msg;
    }
}
